runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: gaetrans.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"